services:

    shinobi-notus-react-dashboard:

        container_name: shinobi-notus-react-dashboard
        
        image: softwareshinobi/shinobi-notus-react-dashboard

        build: 

            context: .

            dockerfile: Dockerfile
  
        restart: unless-stopped

        ports:

            - "3000:3000"

        environment:

            DB_HOST: garuda-agile-ops-database

            DB_PORT: 3306
            
            DB_NAME: garudaops

            DB_USER: garudaops

            DB_PASS: garudaops
